name: myapp
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1 # Replace with your actual version
environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4 # Latest version compatible with Flutter 3.4.3

  dartz: ^0.10.1
  # Service locator
  get_it: ^7.2.0
  # Bloc for state management
  flutter_bloc: ^8.1.1
  # Value equality
  equatable: ^2.0.5
  # Remote API
  connectivity_plus: ^4.0.2
  http: ^0.13.4

  rxdart: ^0.27.5 # Latest version compatible with Flutter 3.4.3
  # Local cache
  shared_preferences: ^2.1.1
  image_picker: ^1.0.2 # Latest version compatible with Flutter 3.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^9.0.0
  build_runner: ^2.3.5
  mockito: ^5.2.0
  flutter_lints: ^3.0.2


  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  #flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

 
  assets:
    - images/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
